services:
  - type: web
    name: nanolens-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: INDEX_NAME
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
